const DISCOUNT_KEYWORDS = [
  { value: 1, label: 'zapatos' },
  { value: 2, label: 'zapatillas' },
  { value: 3, label: 'calzado' },
  { value: 4, label: 'ropa' },
  { value: 5, label: 'accesorios' },
  { value: 6, label: 'camisas' },
  { value: 7, label: 'pantalones' },
  { value: 8, label: 'camisetas' },
  { value: 9, label: 'chaquetas' },
  { value: 10, label: 'chandal' },
  { value: 11, label: 'vestidos' },
  { value: 12, label: 'bolsos' },
  { value: 13, label: 'maletas' },
  { value: 14, label: 'ropa deportiva' },
  { value: 15, label: 'deportes' },
  { value: 16, label: 'electrodomésticos' },
  { value: 17, label: 'electrodomesticos' },
  { value: 18, label: 'electrónica' },
  { value: 19, label: 'electronica' },
  { value: 20, label: 'televisores' },
  { value: 21, label: 'informática' },
  { value: 22, label: 'informatica' },
  { value: 23, label: 'ordenadores' },
  { value: 24, label: 'portátiles' },
  { value: 25, label: 'portatiles' },
  { value: 26, label: 'laptops' },
  { value: 27, label: 'pc' },
  { value: 28, label: 'smartphones' },
  { value: 29, label: 'teléfonos' },
  { value: 30, label: 'telefonos' },
  { value: 31, label: 'tablets' },
  { value: 32, label: 'móviles' },
  { value: 33, label: 'moviles' },
  { value: 34, label: 'celulares' },
  { value: 35, label: 'smartwatches' },
  { value: 36, label: 'smartbands' },
  { value: 37, label: 'viajes' },
  { value: 38, label: 'viajar' },
  { value: 39, label: 'vuelos' },
  { value: 40, label: 'trenes' },
  { value: 41, label: 'hoteles' },
  { value: 42, label: 'restaurantes' },
  { value: 43, label: 'comida' },
  { value: 44, label: 'alimentos' },
  { value: 45, label: 'alimentación' },
  { value: 46, label: 'alimentacion' },
  { value: 47, label: 'bebidas' },
  { value: 48, label: 'cervezas' },
  { value: 49, label: 'juegos' },
  { value: 50, label: 'coworking' },
  { value: 51, label: 'libros' },
  { value: 52, label: 'música' },
  { value: 53, label: 'musica' },
  { value: 54, label: 'películas' },
  { value: 55, label: 'peliculas' },
  { value: 56, label: 'series' },
  { value: 57, label: 'juegos de mesa' },
  { value: 58, label: 'plantas' },
  { value: 59, label: 'jardinería' },
  { value: 60, label: 'jardineria' },
  { value: 61, label: 'decoración' },
  { value: 62, label: 'decoracion' },
  { value: 63, label: 'hogar' },
  { value: 64, label: 'cocina' },
  { value: 65, label: 'flores' },
  { value: 66, label: 'perfumes' },
  { value: 67, label: 'colonias' },
  { value: 68, label: 'cremas' },
  { value: 69, label: 'cosmética' },
  { value: 70, label: 'cosmetica' },
  { value: 71, label: 'maquillaje' },
  { value: 72, label: 'peluches' },
  { value: 73, label: 'outlets' },
  { value: 74, label: 'educación' },
  { value: 75, label: 'educacion' },
  { value: 76, label: 'cursos' },
];

export default DISCOUNT_KEYWORDS;

//The exact same object as before, but the "value" property doesn't repeat and starts from 1
