//TODO: Make sure what is needed to generate a new discount code (in the affiliate networks)

//CLARIFICATIONS:
// 1. brand_logo should be svg or at least a big ennough png

//TODO: try to reorganize offer info
export const OFFERS = [
  {
    //Generated by Mongo
    offer_id: 1,
    offer_external_id: 123,
    title: '5% de descuento en la tienda de Grover',
    brand: {
      //TODO: populate it from the brand_id. For now, keep it like this to desing the front
      brand_name: 'Grover',
      brand_description:
        'Grover es una tienda especializada en artículos de bla bla bla Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    brand_logo: 'logo_svg_src',
    banner: 'banner_src',
    //Try to keep it short, but can be as long as possible if needed
    description:
      'Gracias al cupón de descuento para estudiantes en Grover conseguirás un 20% de descuento en tus compras, ahorra dinero en una gran gama de productos en la tienda de cosméticos Grover',
    //If no affiliate_link, display the discount code component and pass whole offer info
    affiliate_link: 'http://campuscanvas.net',
    //If there is no code, send the needed info to the required API to generate the code and put it in a state
    discount_code: '',
    terms_and_conds: `<p>Set inner HTML. Allow p-tags and ul-tags only</p>`,
    creation_date: new Date(),
    valid_from: new Date(),
    valid_till: new Date(),
    sponsors_box: false,
    /// discount_code | affiliate_link. Leave it for future filterings, consider to use this to decide how to render the front or if there is an affiliate_link.
    type: 'discount_code',
    action_btn_phrase: '',
    likes: 0,
    dislikes: 0,
  },
];
