import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { POSTS } from '@databases/BlogDatabase';

const INITIAL_STATE = {
  posts: [],
  loading: false,
  error: '',
};

//createAsyncThunk is a function that accepts a string for the generated action types and a function called the payload creator, which can be async. That function is the one that can receive arguments in case we need them. The function MUST return a promise. The promise can be resolved with the data we want to use or rejected with an error message. The function will return an object with the action types generated by createAsyncThunk. We can use those action types to add extra reducers to the slice.
export const getPosts = createAsyncThunk(
  'posts/getPosts',
  //First parameter is what we send from the component where we use the action creator. In this case, we are sending the id of the job.
  async () => {
    try {
      // const response = await axios.get(JOBS_URL);
      // return response.data;
      //Create a fake async call to the database with async/await
      return new Promise((resolve, reject) => {
        //Uncomment to simulate an error
        // setTimeout(() => {
        //   reject(
        //     new Error(
        //       'Ha ocurrido un problema al cargar los puestos de trabajo. Inténtalo más tarde.'
        //     )
        //   );
        // }, 2000);
        setTimeout(() => {
          resolve(POSTS);
        }, 800);
      });
    } catch (error) {
      console.log(error);
      return error.message;
    }
  }
);

export const postsSlice = createSlice({
  name: 'posts',
  initialState: INITIAL_STATE,
  reducers: {},
  //Used to handle the state according to the promise status of the createAsyncThunk function.
  extraReducers: (builder) => {
    //We can add a case for the action type generated by createAsyncThunk
    builder
      //In this case, getPosts will generate 3 action types: getPosts/pending, getPosts/fulfilled, getPosts/rejected. We can add a case for each one of them.
      .addCase(getPosts.pending, (state, action) => {
        state.loading = true;
      })
      .addCase(getPosts.fulfilled, (state, action) => {
        state.loading = false;
        state.posts = action.payload;
      })
      .addCase(getPosts.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message;
      });
  },
});

export const selectPosts = (state) => state.posts;

export default postsSlice.reducer;
